# Reference for the RPC commands:
# https://www.qemu.org/docs/master/interop/qemu-ga-ref.html
#
# The following RPCs are allowed as of version 11.0 of qemu-ga
# By definition all other RPCs are blocked. They are listed below for reference.
#
# Allowed:
# guest-fsfreeze-freeze
# guest-fsfreeze-freeze-list
# guest-fsfreeze-status
# guest-fsfreeze-thaw
# guest-fstrim
# guest-get-cpustats
# guest-get-disks
# guest-get-diskstats
# guest-get-memory-block-info
# guest-get-time
# guest-get-vcpus
# guest-info
# guest-network-get-interfaces
# guest-ping
# guest-set-vcpus
# guest-shutdown
# guest-suspend-disk
# guest-suspend-hybrid
# guest-suspend-ram
# guest-sync
# guest-sync-delimited
# guest-get-load
# 
# Blocked:
# guest-exec
# guest-exec-status
# guest-file-close
# guest-file-flush
# guest-file-open
# guest-file-read
# guest-file-seek
# guest-file-write
# guest-get-devices
# guest-get-fsinfo
# guest-get-host-name
# guest-get-memory-blocks
# guest-get-osinfo
# guest-get-timezone
# guest-get-users
# guest-set-memory-blocks
# guest-set-time
# guest-set-user-password
# guest-ssh-add-authorized-keys
# guest-ssh-get-authorized-keys
# guest-ssh-remove-authorized-keys
# guest-network-get-route

[general]
# Debug shows disabled commands on startup but is very chatty. Only enable for a short time.
verbose = 0
allow-rpcs = guest-fsfreeze-freeze;guest-fsfreeze-freeze-list;guest-fsfreeze-status;guest-fsfreeze-thaw;guest-fstrim;guest-get-cpustats;guest-get-disks;guest-get-diskstats;guest-get-memory-block-info;guest-get-time;guest-get-vcpus;guest-info;guest-network-get-interfaces;guest-ping;guest-set-vcpus;guest-shutdown;guest-suspend-disk;guest-suspend-hybrid;guest-suspend-ram;guest-sync;guest-sync-delimited;guest-get-load;

