alias ls='ls --color=auto'
alias ll='ls -FAhl'
alias la='ls -FAh'
alias yolossh='ssh -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=accept-new'
alias ssha='ssh -o ForwardAgent=true'
alias sshs='SKIPTMUX=1 ssh -o SendEnv=SKIPTMUX'
alias grep_uncommented='grep -vE "^\s*(#|$)"'